version: "2.1"

services:
  eureka-server:
    build : eureka-server/
    ports:
      - "8761:8761"
  config-server:
    build : config-server/
    ports:
      - "8888:8888"
  checkout-service:
    build : checkout-service/
    ports:
      - "8082:8082"
  products-service:
    build : products-service/
    ports:
      - "8081:8081"
  payments-service:
    build : payments/
    ports:
      - "8086:8086"
  notificacion-server:
    build : notificacion/
    ports:
      - "8087:8087"
  gateway-server:
    build : gateway/
    ports:
      - "8085:8085"
  rabbit-mq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      